Remove class name from exception.toString().
Before:
  1) intIsInt(com.google.common.truth.IntegerSubjectTest)
  java.lang.AssertionError: Not true that <3> is equal to <4>
    at com.google.common.truth.IntegerSubjectTest.intIsInt(IntegerSubjectTest.java:54)

After:
  1) intIsInt(com.google.common.truth.IntegerSubjectTest)
  Not true that <3> is equal to <4>
    at com.google.common.truth.IntegerSubjectTest.intIsInt(IntegerSubjectTest.java:54)

It's a small but IMO significant amount of noise. And users don't care about the type in the normal case. Or if they do care, they can already tell it's AssertionError because JUnit has classified the test under "failures" rather than "errors." All that's left is the AssertionError/ComparisonFailure distinction, which shouldn't matter much. People can still use instanceof, etc. if they do care, but mostly they shouldn't need to: If they're catching AssertionError specifically, they should probably be implementing a custom FailureStrategy instead.

RELNOTES=n/a

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=180192778