Fix Javadoc generation under Java 11.
Java 11 is what we use for building snapshots, so the Truth Javadocs haven't been updating. ("Fortunately," we haven't been adding APIs :))

The problem is errors like the following:

[ERROR] Exit code: 1 - /home/travis/build/google/truth/core/src/main/java/com/google/common/truth/super/com/google/common/truth/Platform.java:20: error: package jsinterop.annotations does not exist
[ERROR] import static jsinterop.annotations.JsPackage.GLOBAL;
[ERROR]                                    ^

Example failure: https://travis-ci.org/google/truth/builds/636435498

It turns out that this error is only a warning under Java 8.

Also, while here, edit the comment from CL 289440196 to reflect that the problem isn't exclusive to Samsung.

RELNOTES=n/a

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=289654387