Stop explicitly requesting Javadoc and source jars.
Thanks to the configuration changes of cl/805973207, snapshot deployment is [still broken but in a new way](https://github.com/google/truth/actions/runs/17657020721/job/50182316838):

```
[INFO] >>> source:3.3.1:jar (default-cli) > generate-sources @ truth >>>
...
[INFO] <<< source:3.3.1:jar (default-cli) < generate-sources @ truth <<<
[INFO]
[INFO]
[INFO] --- source:3.3.1:jar (default-cli) @ truth ---
[INFO] Building jar: /home/runner/work/truth/truth/core/target/truth-HEAD-SNAPSHOT-sources.jar
...
[INFO] >>> source:3.3.1:jar (attach-sources) > generate-sources @ truth >>>
...
[INFO] <<< source:3.3.1:jar (attach-sources) < generate-sources @ truth <<<
[INFO]
[INFO]
[INFO] --- source:3.3.1:jar (attach-sources) @ truth ---
[INFO] Building jar: /home/runner/work/truth/truth/core/target/truth-HEAD-SNAPSHOT-sources.jar
Error:  We have duplicated artifacts attached.
```

The problem is that we're not only requesting Javadoc and source jars explicitly on the command line (which triggers the `default-cli` execution) but also getting them automatically because of the configuration changes of my CL.

The solution is to stop requesting them explicitly.

That matches [what we do for Guava snapshots](https://github.com/google/guava/blob/087f2c4a8012fb1256f80f6f776df0e8706af683/util/deploy_snapshot.sh#L8). It also matches what we do for non-snapshot releases.

RELNOTES=n/a
PiperOrigin-RevId: 807772725