Rename prepend() to "append," which is what it actually does. And since there's already an append(), I've actually parameterized it rather than introduced an overload.
Our existing tests already verify that we're appending, rather than prepending. Here's how ThrowableSubjectTest would break if we started actually prepending:

Existing behavior of appending:
Unexpected cause for java.lang.Exception: Unexpected cause for java.lang.RuntimeException: Unexpected message for java.io.IOException: expected:<[message]> but was:<[buzz]>

If we were actually prepending:
Unexpected message for java.io.IOException: Unexpected cause for java.lang.RuntimeException: Unexpected cause for java.lang.Exception: expected:<[message]> but was:<[buzz]>

I think the appending behavior makes more sense here, since it puts the "Unexpected message" part near the actual message. That said, I ultimately don't want for ThrowableSubject to use withMessage() in this way, so don't put too much weight on that. The main point is that this is the way we've been doing it since before FailureMetadata existed. If we want to revisit that someday, we can.

Also, clarify behavior in the docs for the relevant public method, withMessage().

RELNOTES=n/a

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=180288182